### ISSUE TITLE
Third-Party Apps Security Review

### ISSUE THREAD

**Issue by g4brielvs** [worldbank/.github#4]
Before #3, third-party apps require security review by the Office of Information Security.

**Comment by g4brielvs** [comment]
@quehill The OIS accreditation for the WB GitHub org's third party apps should be completed this week.

**Comment by g4brielvs** [comment]
@quehill Could you please provide a status update on the OIS accreditation?

**Comment by quehill** [comment]
Response from OIS is by EOD 7/2 at the latest. I am continuing to bother them incessantly until it's done.

**Comment by quehill** [comment]
@g4brielvs OIS accreditation is complete. We are ready to proceed with the enterprise migration.
